### ISSUE TITLE
python33: basic-usage fails with SyntaxErrors

### ISSUE THREAD

**Issue by domcleal** [sclorg/sclo-ci-tests#12]
- https://ci.centos.org/view/SCLo/job/SCLo-python33-rh-C6-x86_64/
- https://ci.centos.org/view/SCLo/job/SCLo-python33-rh-C7-x86_64/

basic-usage tests for python33 are failing with SyntaxErrors when using Django.

<pre>
++ scl enable python33 -- python -c 'print('\''Hello World'\'')'
+ out='Hello World'
+ '[' 'Hello World' '!=' 'Hello World' ']'
+ scl enable python33 -- easy_install pip
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
+ scl enable python33 -- easy_install Django
no previously-included directories found matching 'django/contrib/admin/bin'
warning: no previously-included files matching '__pycache__' found under directory '*'
  File "build/bdist.linux-x86_64/egg/django/conf/app_template/models.py", line 1
    {{ unicode_literals }}from django.db import models
                             ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/django/conf/app_template/apps.py", line 1
    {{ unicode_literals }}from django.apps import AppConfig
                             ^
SyntaxError: invalid syntax

  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/conf/app_template/models.py", line 1
    {{ unicode_literals }}from django.db import models
                             ^
SyntaxError: invalid syntax

  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/conf/app_template/apps.py", line 1
    {{ unicode_literals }}from django.apps import AppConfig
                             ^
SyntaxError: invalid syntax

+ scl enable python33 -- pip install Flask
+ scl enable python33 -- python -c 'from flask import Flask'
+ scl enable python33 -- python -c 'from django.conf.urls import patterns, url'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/conf/urls/__init__.py", line 5, in <module>
    from django.core.urlresolvers import (
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/core/urlresolvers.py", line 17, in <module>
    from django.http import Http404
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/http/__init__.py", line 2, in <module>
    from django.http.request import (
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/http/request.py", line 10, in <module>
    from django.core import signing
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/core/signing.py", line 51, in <module>
    from django.utils.module_loading import import_string
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/Django-1.9.1-py3.3.egg/django/utils/module_loading.py", line 67, in <module>
    from importlib.util import find_spec as importlib_find
ImportError: cannot import name find_spec
</pre>

**Comment by domcleal** [comment]
Fixed by 3f200834a97703bf02659614877605dfa70615b6.
